image: node:14-alpine

stages:
  - deploy

cache:
  paths:
    - node_modules/

heroku-deploy:
  stage: deploy
  image: ruby:latest
  script:
    - echo 'Heroku deployment'
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - echo DB_CONNECTION=$API_URL_test >> .env
    - gem install node
    - node -v
    - npm -v
    - npm i -g @nestjs/cli
    - npm run prebuild
    - npm run build
    - dpl --provider=heroku --app=$HEROKU_APP --api-key=$HEROKU_API_KEY
  only:
    - master
    - setup-gitlab-ci-and-heroku-deploy
