image: node:14-alpine

stages:
  - init
  - lint
  - build
  - deploy


cache:
  paths:
    - node_modules/

init:
  stage: init
  script:
    - node -v
    - npm -v
    - npm i -g @nestjs/cli
    - npm i --silent

lint:
  stage: lint
  dependencies:
    - init
  script:
    - npm run lint

build:
  stage: build
  dependencies:
    - init
  script:
    - echo DB_CONNECTION=$API_URL_test >> .env
    - npm run prebuild
    - npm run build

heroku-deploy:
  stage: deploy
  dependencies:
    - build
  script:
    - git push https://$HEROKU_USER:$HEROKU_API_KEY@git.heroku.com/hotel-offers1-backend.git HEAD:master
      - echo "Deployed to heroku server"
  environment:
    name: prod
    url: https://hotel-offers1-backend.herokuapp.com/
  only:
    - master
    - setup-gitlab-ci-and-heroku-deploy
