image: ruby:latest

before_script:
  - apt-get update -qy
  - apt-get install -y ruby-dev
  - gem install dpl

stages:
  - deploy

cache:
  paths:
    - node_modules/

heroku-deploy:
  stage: deploy
  script:
    - echo 'Heroku deployment'
    - echo DB_CONNECTION=$API_URL_test >> .env
    - sudo dnf install -y gcc-c++ make
    - curl -sL https://rpm.nodesource.com/setup_14.x | sudo -E bash -
    - sudo dnf install nodejs
    - sudo dnf install npm
    - node -v
    - npm -v
    - npm i -g @nestjs/cli
    - npm run prebuild
    - npm run build
    - dpl --provider=heroku --app=$HEROKU_APP --api-key=$HEROKU_API_KEY
  only:
    - master
    - setup-gitlab-ci-and-heroku-deploy
