image: ruby:latest

before_script:
  - apt-get update -qy
  - apt-get install -y ruby-dev
  - gem install dpl

stages:
  - production

cache:
  paths:
    - node_modules/

production:
  stage: production
  script:
    - echo DB_CONNECTION=$API_URL_test >> .env
    - pwd
    - sudo apt install nodejs
    - node -v
    - npm run prebuild
    - npm run build
    - dpl --provider=heroku --app=$HEROKU_APP --api-key=$HEROKU_API_KEY
  only:
    - master
    - setup-gitlab-ci-and-heroku-deploy
