image: node:14-alpine

stages:
  - lint
  - build

lint:
  stage: lint
  script:
    - npm install --silent
    - npm run lint

build:
  stage: build
  dependencies:
    - lint
  script:
    - npm run prebuild
    - npm run build
  artifacts:
    paths:
      - dist/




